nasmon:
  #######################################
  # Serial config
  #######################################
  port: COM11
  baud_rate: 115200
  timeout: 2

  #######################################
  # Page config
  #######################################
  page_directory: ./pages